// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_unstructured

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func UnstructuredProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_key": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				Description:         "The API key for the Unstructured API",
				MarkdownDescription: "The API key for the Unstructured API",
			},
			"endpoint": schema.StringAttribute{
				Optional:            true,
				Description:         "The endpoint of the API",
				MarkdownDescription: "The endpoint of the API",
			},
		},
	}
}

type UnstructuredModel struct {
	ApiKey   types.String `tfsdk:"api_key"`
	Endpoint types.String `tfsdk:"endpoint"`
}
