// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_job

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func JobDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required: true,
			},
			"input_file_ids": schema.ListAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"job_type": schema.StringAttribute{
				Computed: true,
			},
			"output_node_files": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"file_id": schema.StringAttribute{
							Computed: true,
						},
						"node_id": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: OutputNodeFilesType{
						ObjectType: types.ObjectType{
							AttrTypes: OutputNodeFilesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"runtime": schema.StringAttribute{
				Computed: true,
			},
			"status": schema.StringAttribute{
				Computed: true,
			},
			"workflow_id": schema.StringAttribute{
				Computed: true,
			},
			"workflow_name": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type JobModel struct {
	CreatedAt       types.String `tfsdk:"created_at"`
	Id              types.String `tfsdk:"id"`
	InputFileIds    types.List   `tfsdk:"input_file_ids"`
	JobType         types.String `tfsdk:"job_type"`
	OutputNodeFiles types.List   `tfsdk:"output_node_files"`
	Runtime         types.String `tfsdk:"runtime"`
	Status          types.String `tfsdk:"status"`
	WorkflowId      types.String `tfsdk:"workflow_id"`
	WorkflowName    types.String `tfsdk:"workflow_name"`
}

var _ basetypes.ObjectTypable = OutputNodeFilesType{}

type OutputNodeFilesType struct {
	basetypes.ObjectType
}

func (t OutputNodeFilesType) Equal(o attr.Type) bool {
	other, ok := o.(OutputNodeFilesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t OutputNodeFilesType) String() string {
	return "OutputNodeFilesType"
}

func (t OutputNodeFilesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	fileIdAttribute, ok := attributes["file_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`file_id is missing from object`)

		return nil, diags
	}

	fileIdVal, ok := fileIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`file_id expected to be basetypes.StringValue, was: %T`, fileIdAttribute))
	}

	nodeIdAttribute, ok := attributes["node_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`node_id is missing from object`)

		return nil, diags
	}

	nodeIdVal, ok := nodeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`node_id expected to be basetypes.StringValue, was: %T`, nodeIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return OutputNodeFilesValue{
		FileId: fileIdVal,
		NodeId: nodeIdVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewOutputNodeFilesValueNull() OutputNodeFilesValue {
	return OutputNodeFilesValue{
		state: attr.ValueStateNull,
	}
}

func NewOutputNodeFilesValueUnknown() OutputNodeFilesValue {
	return OutputNodeFilesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewOutputNodeFilesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (OutputNodeFilesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing OutputNodeFilesValue Attribute Value",
				"While creating a OutputNodeFilesValue value, a missing attribute value was detected. "+
					"A OutputNodeFilesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OutputNodeFilesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid OutputNodeFilesValue Attribute Type",
				"While creating a OutputNodeFilesValue value, an invalid attribute value was detected. "+
					"A OutputNodeFilesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OutputNodeFilesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("OutputNodeFilesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra OutputNodeFilesValue Attribute Value",
				"While creating a OutputNodeFilesValue value, an extra attribute value was detected. "+
					"A OutputNodeFilesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra OutputNodeFilesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOutputNodeFilesValueUnknown(), diags
	}

	fileIdAttribute, ok := attributes["file_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`file_id is missing from object`)

		return NewOutputNodeFilesValueUnknown(), diags
	}

	fileIdVal, ok := fileIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`file_id expected to be basetypes.StringValue, was: %T`, fileIdAttribute))
	}

	nodeIdAttribute, ok := attributes["node_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`node_id is missing from object`)

		return NewOutputNodeFilesValueUnknown(), diags
	}

	nodeIdVal, ok := nodeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`node_id expected to be basetypes.StringValue, was: %T`, nodeIdAttribute))
	}

	if diags.HasError() {
		return NewOutputNodeFilesValueUnknown(), diags
	}

	return OutputNodeFilesValue{
		FileId: fileIdVal,
		NodeId: nodeIdVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewOutputNodeFilesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) OutputNodeFilesValue {
	object, diags := NewOutputNodeFilesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOutputNodeFilesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t OutputNodeFilesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOutputNodeFilesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOutputNodeFilesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOutputNodeFilesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOutputNodeFilesValueMust(OutputNodeFilesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t OutputNodeFilesType) ValueType(ctx context.Context) attr.Value {
	return OutputNodeFilesValue{}
}

var _ basetypes.ObjectValuable = OutputNodeFilesValue{}

type OutputNodeFilesValue struct {
	FileId basetypes.StringValue `tfsdk:"file_id"`
	NodeId basetypes.StringValue `tfsdk:"node_id"`
	state  attr.ValueState
}

func (v OutputNodeFilesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["file_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["node_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.FileId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["file_id"] = val

		val, err = v.NodeId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["node_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v OutputNodeFilesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v OutputNodeFilesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v OutputNodeFilesValue) String() string {
	return "OutputNodeFilesValue"
}

func (v OutputNodeFilesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"file_id": basetypes.StringType{},
		"node_id": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"file_id": v.FileId,
			"node_id": v.NodeId,
		})

	return objVal, diags
}

func (v OutputNodeFilesValue) Equal(o attr.Value) bool {
	other, ok := o.(OutputNodeFilesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.FileId.Equal(other.FileId) {
		return false
	}

	if !v.NodeId.Equal(other.NodeId) {
		return false
	}

	return true
}

func (v OutputNodeFilesValue) Type(ctx context.Context) attr.Type {
	return OutputNodeFilesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v OutputNodeFilesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"file_id": basetypes.StringType{},
		"node_id": basetypes.StringType{},
	}
}
